### ISSUE TITLE
error : "/lib/jars" not found

### ISSUE THREAD

**Issue by kazurof** [ayt-szk/learning-apache-spark#1]
Dear author,

I got error message below after I executed. `docker-compose up -d`

```
 => ERROR [local_spark-master 8/9] COPY lib/jars /usr/local/lib/jars                                               0.0s
------
 > [local_spark-master 8/9] COPY lib/jars /usr/local/lib/jars:
------
failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/lib/jars" not found: not found

```
I believe some file under `lib/jars` might be needed , or this line should be deleted.

https://github.com/ayt-szk/learning-apache-spark/blob/main/build/master/Dockerfile#L20

Thanks in advance.

**Comment by ayt-szk** [comment]
@kazurof 
Thank you for the issue!

I just executed `docker-compose up -d` in my environment and got the same result.

So, I deleted the command to copy 'lib/jars' from the Dockerfile.

I confirmed that it works as expected if this line was deleted.

I've already committed the fix.

Thank you!

**Comment by kazurof** [comment]
Thank you for your quick response!
